version: "2"
services:
  frontend-ziltag.com:
    container_name: ${CONTAINER_NAME}
    build: .
    image: ziltag/frontend-ziltag.com
    command: npm run serve
    links:
      - ziltag.dev
    ports:
      - "${PORT}:2000"
      - "${SSL_PORT}:2001"
      - "${DEBUG_PORT}:1999"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  ziltag.dev:
    image: ziltag/ziltag.com
    links:
      - db

  ziltag-plugin:
    image: ziltag/ziltag-plugin

  db:
    image: postgres:9.4
    environment:
      POSTGRES_DB: ziltag_development
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
