version: "2"
services:
  frontend-ziltag.com:
    container_name: ${CONTAINER_NAME}
    build: .
    image: frontend-ziltag.com
    command: npm run serve
    ports:
      - "${PORT}:2000"
      - "${SSL_PORT}:2001"
      - "${DEBUG_PORT}:1999"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - app

  ziltag-plugin:
    image: localhost:5000/ziltag-plugin
    command: npm run serve

  db:
    image: postgres:9.4
    volumes:
      - ziltag-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ziltag_development

  app:
    image: ziltag/ziltag.com
    depends_on:
      - db

volumes:
  ziltag-db:
  node_modules:
